[package]
name = "minilisp"
version = "0.1.0"
edition = "2024"
authors = ["Linus Kirkwood <linuskirkwood@gmail.com>"]
license = "LGPL-3.0-only"
readme = "README.org"

[dependencies]
anyhow = "1.0"
lazy_static = "1.5"

[profile.dist]
inherits = "release"
lto = true
codegen-units = 1
